### ISSUE TITLE
Support for ARM

### ISSUE THREAD

**Issue by tristan-k** [moritzfl/docker-virtualhere#1]
Thanks for the docker image. Can you add support for [ARM](https://www.virtualhere.com/sites/default/files/usbserver/vhusbdarm) (Raspberry Pi 4)?

**Comment by moritzfl** [comment]
If I had a Raspberry Pi for testing and building, I would. But I do not have that hardware accessible. The required changes to my existing docker image should be minimal though (basically: replace ubuntu with an arm compatible version, replace the download link for virtualhere with the link for arm).

**Comment by moritzfl** [comment]
If anyone is willing to do this for arm, fork my repo and go for it.

**Comment by tristan-k** [comment]
I created a [pull request](https://github.com/moritzfl/docker-virtualhere/pull/2/commits/08d0000ee5550d6f6f7511005c7675d7d9ba828b).
