### ISSUE TITLE
unexpected operator

### ISSUE THREAD

**Issue by dhstsw** [moritzfl/docker-virtualhere#3]
Hi,
launching the container (KVM on Unraid) log reports the following:

`/etc/start-virtualhere.sh: 6: [: x86_64: unexpected operator`

Then it detects my USB devices, downloads and try to launch the wrong (ARM) executable and exists:

`./vhusbdarm: 1: ./vhusbdarm: Syntax error: word unexpected (expecting ")")`

**Comment by moritzfl** [comment]
I hope it works now - Docker Hub ~~is still building but I expect that to go well~~ apparently already finished. Would be nice if you could report back if that fixed it for you.

**Comment by dhstsw** [comment]
Yup, working fine now.

Thanks!

Il giorno dom 12 gen 2020 alle ore 18:17 Moritz <notifications@github.com>
ha scritto:

**Comment by dhstsw** [comment]
Maybe in next revision, if any there will be, would be nice to be able to specify arguments for the server, as (for example) -r /data/log.txt to save a logfile.
Thanks!

**Comment by moritzfl** [comment]
Thanks for the feedback - I think this ticket can be closed! 
I also appreciate your suggestion but I don't think a quickly hacked together logging solution for within the bash scripts would benefit this project.
To get to the log of a given container, you can always execute ```docker logs CONTAINERNAME```on your host. And if more sophisticated logging is required, you can take a look at dockers logging drivers: https://docs.docker.com/config/containers/logging/configure/
